CREATE TABLE tokens (
  id      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  user_id BIGINT UNSIGNED NOT NULL,
  token   VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);
ALTER TABLE tokens ADD CONSTRAINT USER_FK FOREIGN KEY (user_id) REFERENCES users (id)
  ON UPDATE RESTRICT
  ON DELETE CASCADE;